_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
                - 62
            "4": 3.8.10
            "5": 0.19.9
            "8":
                - 5
            "10":
                - 20
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 64
clip:
    value: 5
compression_dim:
    value: 100
embedding_size:
    value: 300
ensemble_member:
    value: 3
hidden_size:
    value: 256
learning_rate:
    value: 1
max_epochs:
    value: 100
model_type:
    value: RNN
n_layers:
    value: 1
optimizer:
    value: SGD
patience:
    value: 3
seed:
    value: 44
