_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.10
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size_eval:
    value: 128
batch_size_train:
    value: 32
clip_gradient:
    value: 5
emb_dropout_rate:
    value: 0.5
embedding_size:
    value: 650
epochs:
    value: 40
hidden_size:
    value: 650
learning_rate:
    value: 0.001
lr_decay_epoch_threshold:
    value: 6
lr_decay_factor:
    value: 0.5
lstm_dropout_rate:
    value: 0.5
n_layers:
    value: 2
optimizer:
    value: AdamW
out_dropout_rate:
    value: 0.5
