_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
                - 62
            "4": 3.8.10
            "5": 0.19.9
            "6": 4.46.3
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size_eval:
    value: 64
batch_size_train:
    value: 32
bert_model:
    value: bert-base-uncased
dropout_prob:
    value: 0.15
epochs:
    value: 15
learning_rate:
    value: 5e-05
num_intent_labels:
    value: 26
num_slot_labels:
    value: 131
optimizer:
    value: AdamW
patience:
    value: 3
scheduler:
    value: LinearWarmup
warmup_steps:
    value: 0
