_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.8.10
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size_eval:
    value: 64
batch_size_train:
    value: 128
clip_gradient:
    value: 5
dropout:
    value: 0.3
embedding_size:
    value: 300
epochs:
    value: 200
hidden_size:
    value: 500
learning_rate:
    value: 0.0001
n_layers:
    value: 2
optimizer:
    value: Adam
patience:
    value: 3
